export const HIVE_GENERATIVE_MODELS = new Set([
  "gemini3", "steadydancer", "seedream", "higgsfield", "wan", "gemini",
  "stablediffusion", "flux", "seedance2", "other_image_generators",
  "grokimagine", "heygen", "dalle", "gptimage2", "adobefirefly",
  "midjourney", "reve", "flux2", "luma", "personalive", "grok",
  "sdxlinpaint", "zimage", "kandinsky", "pika", "qwen", "hunyuan",
  "moonvalley", "veo3", "imagen", "4o", "liveportrait", "gan",
  "longcat", "stablediffusionxl", "dreamid", "krea", "kling",
  "leonardo", "hedra", "runway", "var", "cogvideos", "wuerstchen",
  "bria", "gptimage1_5", "recraft", "mai", "mcnet", "amused",
  "imagen4", "imagineart", "scail", "stablecascade", "seedance",
  "ideogram", "meta", "janus", "happyhorse", "omnigen", "mochi",
  "stablediffusioninpaint", "pyramidflows", "sora2", "ernie",
  "pixart", "cogview", "glide", "hailuo", "transpixar", "pixverse",
  "lcm", "emu3", "sadtalker", "viduq2", "titan", "lucid", "bagel",
  "sana", "aniportrait", "dmd2", "infinity", "luminagpt", "vibe",
  "ltx", "blip3o", "vqdiffusion", "ovis", "switti", "bingimagecreator",
  "deepfloyd", "flashvideo", "hidream", "sora", "hallo", "ray3",
  "sanavideo", "makeittalk", "cosmos", "haiper",
]);
