drop table if exists public.public_scan_limits;
drop table if exists public.waitlist;
drop function if exists public.increment_scan_count;

create table public.public_scan_limits (
  id bigint generated by default as identity primary key,
  ip_address text not null unique,
  scan_count int not null default 0,
  window_start timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.waitlist (
  id bigint generated by default as identity primary key,
  email text not null,
  created_at timestamptz not null default now()
);

alter table public.public_scan_limits disable row level security;
alter table public.waitlist disable row level security;


